name: Run Robot Tests

on:
  push:
    paths:
      - 'CriticalFlows/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install robotframework selenium robotframework-seleniumlibrary

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Robot Framework Tests
        run: robot CriticalFlows/
