name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary webdriver-manager
        # Add any other Python dependencies your project needs here

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Run Robot Framework tests
      run: |
        # The CHROME_OPTIONS are now handled in Robot Framework's BrowserKeywords.robot
        # You can remove or comment out the line below as it's now redundant:
        # export CHROME_OPTIONS="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --window-size=1920,1080 --remote-debugging-port=9222 --disable-setuid-sandbox --disable-features=UtilityProcessSandbox --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --no-first-run --no-default-browser-check --no-zygote --single-process --ignore-certificate-errors --disable-popup-blocking --disable-infobars"
        
        robot CriticalFlows/

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: output/
        if-no-files-found: ignore