name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary webdriver-manager

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: List Project Files (Debug)
      run: |
        echo "==== FILE STRUCTURE ===="
        find .

    - name: Run All Robot Framework Tests
      run: |
        robot -L TRACE -d output/ CriticalFlows/

    - name: Upload Robot Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: output/
        if-no-files-found: ignore