name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Or a specific version like '3.9', '3.10', etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary # Assuming these are your main dependencies

    - name: Run Robot Framework tests
      run: |
        robot CriticalFlows/ # <<<--- THIS IS THE CHANGE YOU NEED TO MAKE

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: output/
        if-no-files-found: ignore