name: Robot Framework Tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Robot dependencies
      run: |
        pip install robotframework robotframework-seleniumlibrary webdriver-manager

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: List Project Files (Debug)
      run: |
        echo "==== PROJECT STRUCTURE ===="
        find .

    - name: Run Robot Framework Tests
      run: |
        robot -L TRACE -d output/ CriticalFlows/sanity.robot

    - name: Upload Robot Framework Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: output/
        if-no-files-found: ignore