name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework selenium robotframework-seleniumlibrary chromedriver-autoinstaller

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Robot Tests
        env:
          PATH: /usr/bin:$PATH
        run: |
          python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          robot CriticalFlows/

